source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GifCameraController_Example' do
  pod 'GifCameraController', :path => '../'
end

target 'GifCameraController_Tests' do
  pod 'GifCameraController', :path => '../'

  pod 'Quick'
  pod 'Nimble'
end
